ALTER TABLE student MODIFY COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ADD CONSTRAINT mark_check CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject ADD CONSTRAINT subject_check CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype ADD CONSTRAINT name_check UNIQUE (name);
ALTER TABLE payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount decimal NOT NULL;
ALTER TABLE payment MODIFY COLUMN payment_date DateTime NOT NULL;